# Site settings
title: Abhas Tandon
email: your-email@domain.com
description: > # I am a half stack developer (Front-End). Languages that I speak are JavaScript (mother tongue) - with blend of HTML and CSS. Familiar with PHP & JAVA/C/C++
baseurl: "/resume" # the subpath of your site, e.g. /blog/
url: "https://abhas9.github.io" # the base hostname & protocol for your site
twitter_username: abhas9
github_username:  abhas9

# Build settings
markdown: kramdown
kramdown: 
  parse_block_html: true